### ISSUE TITLE
Remove grey dots in content analysis

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#25]
Currently, in many places in the content analysis, grey bullets are shown:
<img width="554" alt="schermafbeelding_2018-02-28_om_10_34_08" src="https://user-images.githubusercontent.com/17744553/36780333-f694b15e-1c72-11e8-86d1-15a9f38f8b5d.png">
Remove them. Please check all tabs.

If you think the styling from Gutenberg is too aggressive, and this should be fixed in Gutenberg instead of in wordpress-seo, please create an issue on their repo.

**Comment by igorschoester** [comment]
This style is the source of that:
```css
.gutenberg ul:not(.wp-block-gallery) {
    list-style-type: disc;
}
```
